# Generated by Django 3.1.1 on 2020-09-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='statte',
            new_name='state',
        ),
    ]
